apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: react-app
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 127.0.0.1:30400/node-test:latest
          ports:
            - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: react-app.medikar.com.br
      http:
        paths:
          - path: /
            backend:
              serviceName: react-app
              servicePort: http
