apiVersion: v1
kind: Service
metadata:
  name: rcapp
  labels:
    app: rapp
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001

  selector:
    app: rcapp
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rcapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rcapp
    spec:
      containers:
        - name: rcapp
          image: "127.0.0.1:30400/app:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
